server:
  port: 8761
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost

    

  client:
#as a client it will not get regsitered 
    register-with-eureka: false 
#don't fetch registry info from server
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

