spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: orderservice
  application:
    name: order-service

server:
  port: 8085

    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
